### ISSUE TITLE
Failing config files

### ISSUE THREAD

**Issue by agyaglikci** [HewlettPackard/cacti#6]
Most of the config files in the repo lead to either a `segmentation fault` or a `floating point error`. I basically clone, compile, and run cacti w/o touching anything. I use a `Ubuntu 16.04.3 LTS` system with kernel `4.15.0-24-generic`. Could you take a look at that? 

You can find a summary of these config files below: 

This is what I do:
```
git clone https://github.com/HewlettPackard/cacti.git Cacti7
cd Cacti7
make
./cacti -infile sample_config_files/lpddr3_cache.cfg  
```
Here are the errors I get with the provided config files: 

| Config File  | Behavior |
| ------------- | ------------- |
| cache.cfg  | Finishes successfully | 
| ddr3.cfg  | Throws `Segmentation fault (core dumped)`  | 
| dram.cfg  | Throws `Floating point exception (core dumped)` | 
| lpddr.cfg  | Throws `Segmentation fault (core dumped)`  | 
| 2DDRAM_micron1Gb.cfg | Throws `Floating point exception (core dumped)` | 
| 2DDRAM_Samsung2GbDDR2.cfg | Throws `Floating point exception (core dumped)` | 
| 3DDRAM_Samsung3D8Gb_extened.cfg | Throws `Floating point exception (core dumped)` | 
| sample_config_files/diff_ddr3_cache.cfg |  Quits with `num_clk should be greater than zero!`| 
| sample_config_files/ddr3_cache.cfg | Throws `Segmentation fault (core dumped)`  | 
| sample_config_files/lpddr3_cache.cfg | Throws `Segmentation fault (core dumped)`  | 
| sample_config_files/wideio_cache.cfg | Throws `Segmentation fault (core dumped)`  | 

## Backtrace of `Segmentation fault`:
```
Thread 1 "cacti" received signal SIGSEGV, Segmentation fault.
0x0000000000473d8e in find_all_bobs (memcad_params=0x0) at memcad.cc:396
396                     int last_bw =(*memcad_all_channels)[0]->bandwidth;
(gdb) bt
#0  0x0000000000473d8e in find_all_bobs (memcad_params=0x0) at memcad.cc:396
#1  0x0000000000474a1e in solve_memcad (memcad_params=0x7fffffff3310) at memcad.cc:595
#2  0x00000000004207c3 in cacti_interface (infile_name=...) at io.cc:1344
#3  0x0000000000411fd3 in main (argc=0, argv=0x656c69666e692d) at main.cc:78
```
*Segmentation fault* happens after logging the `Low-swing wire` stats. So until that point some time/area/power components are already reported. But the *segmentation fault* makes me suspicious about the correctness. Could you check that? 

## Backtrace of ` Floating point exception`
```
Program received signal SIGFPE, Arithmetic exception.
0x000000000045fe31 in IOTechParam::IOTechParam (this=0x6ad070, g_ip=0x1400000000, io_type1=32767, num_mem_dq=-51952, mem_data_width=0, num_dq=7000176, connection=0, num_loads=1, freq=0) at extio_technology.cc:918
918                     (num_dq/mem_data_width)/(g_ip->num_clk/2); 
(gdb) bt
#0  0x000000000045fe31 in IOTechParam::IOTechParam (this=0x6ad070, g_ip=0x1400000000, io_type1=32767, num_mem_dq=-51952, mem_data_width=0, num_dq=7000176, connection=0, num_loads=1, freq=0) at extio_technology.cc:918
#1  0x00000000004206cf in cacti_interface (infile_name=...) at io.cc:1292
#2  0x0000000000411fd3 in main (argc=0, argv=0x656c69666e692d) at main.cc:78
```
*Floating point exception* happens directly after printing the configs, so no results are reported.

**Comment by geraldofojunior** [comment]
I'm facing the same problem at the moment. Any suggestion what could be the issue?
Thanks.

**Comment by yinlee** [comment]
I meet the same question. I try to connect with the authors by email and they all reject the email. I feel curious about it. I first thought that it is my fault.

**Comment by nicmcd** [comment]
Hello! Sorry for the lack of support here. I created this repo but am not the author of this software. I'm working to get someone supporting this.

**Comment by xinx2013** [comment]
Maybe lacking some default configuration values. Add the 'default configuration values ...' part (line 185) in cache.cfg to other cfg files. It may work.

**Comment by MustafaFayez** [comment]
> Maybe lacking some default configuration values. Add the 'default configuration values ...' part (line 185) in cache.cfg to other cfg files. It may work.

I had the same problem and tried that with dram.cfg file and it worked! thanks.

**Comment by bagchi95aritra** [comment]
The fix is working. But if the size is specified as 8 GB, it is not working. It works for size less than 1 GB. Any lead on this?
